apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: student
  name: student
spec:
  containers:
  - image: nginx
    name: student
    resources: {}
  tolerations:
  - effect: NoSchedule
    key: department 
    value: computer 
    operator: Equal
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
