kind: Deployment
apiVersion: apps/v1
metadata:
  name: demo-volume-app
  namespace: demo-volume-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: demo-volume-app
  template:
    metadata:
      labels:
        k8s-app: demo-volume-app
    spec:
      volumes:
      - name: demo-volume-deployment
        persistentVolumeClaim:
          claimName: demo-volume-claim
      containers:
      - name: busybox
        image: busybox
        command: ["/bin/sh","-c"]
        args: ["echo 'Hello Youtube' > /data/hello.txt ; sleep 50000"]
        volumeMounts:
        - name: demo-volume-deployment
          mountPath: /data
